# -*- coding: utf-8 -*-
"""Functions Exercises.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TfEFQHseq9EZw6gnqHWPaJn1qd4fZbaD

# **Exercise 1 Function Basic**
"""

# Write a function get_simple_interest(principal, rate, time) to calculate and return simple interest based on given principal, rate and time.
def get_simple_interest(principal,rate,time):
  simple_interest= (principal*rate*time)/100
  return simple_interest

result=get_simple_interest(120000,13,5)
print(f"Simple interest: {result:.2f}")


# Write a function get_rectangle_area_perimeter(length, width) to calculate and return area and perimeter of a rectangle based on length and width.
def  get_rectangle_area_perimeter(length, width):
  rectangle_area=length*width
  rectangle_perimeter=2*(length+width)
  return rectangle_area, rectangle_perimeter

area,perimeter=get_rectangle_area_perimeter(400,200) #unpacking the values for cleaner output
print(f"Area Rectangle:{area}");
print(f"Perimeter of Rectangle:{perimeter}")


# Write a function is_palindrome(string) to check if a given string is palindrome or not. Return True if it is palindrome else return False.
def is_palindrome(name):
  reverse_name=name[::-1]
  if(name==reverse_name):
    return True
  else:
    return False
result=is_palindrome("level");
print(result)


# Write a function count_vowels(string) return the number of vowels in a given string.
def count_vowels(word):
  word=word.lower();
  counter=(word.count('a')+ word.count('e')+ word.count('i')+
           word.count('o')+ word.count('u'))
  return counter

result=count_vowels("Aeroplane")
print(f"Total Vowels:{result}")


# def count_vowels(word):
#   count=0
#   for char in word:
#     if char.lower() in 'aeiou':
#       count+=1;
#   return count
# result=count_vowels("Aeroplane")
# print(f"Total Vowels:{result}")


# Write a function  get_square_root(num) to return the square root of a given number.
def get_square_root(num):
  square_root=num**0.5
  return square_root
result=get_square_root(7)
print(f"Square root:{result}")

"""# Exercise 2: Using **Functions**"""
# Write a lambda function to calculate cube of a number.
get_cube=lambda number:number**3
print(get_cube(7))

# Store my_num as [1, 4, 7, 9, 12, 18]. Used filter function to select multiple of 3.
my_num =[1, 4, 7, 9, 12, 18]
def multiple_checker(num):
  if(num%3==0):
    return num
result=list(filter(multiple_checker,my_num));
print(result)

#OR LAMBDA

# Store my_num as [1, 4, 7]. Used map function to calculate cube of each number.
my_num=[1, 4, 7]
cube_functions= lambda x:x**3
cube_numbers=list(map(cube_functions,my_num))
print(cube_numbers);


# Store my_num as [1, 5, 7, 9]. Used reduce function to calculate product of these.
from functools import reduce
my_num=[1, 5, 7, 9]
product_function=lambda x,y:x*y
product=reduce(product_function,my_num)
print(product)


# Write a function get_product_remainder(num_1, num_2) that returns product and remainder of two numbers
def get_product_remainder(num_1, num_2):
  if(num_2==0):
    return "Error","Division By Zero"
  product_func=num_1*num_2
  remainder_func=num_1%num_2
  return product_func, remainder_func

product,remainder=get_product_remainder(12,5)
print(f"product:{product}");
print(f"remainder:{remainder}")


# Write a function sum_all() that takes n number of arguments and returns their sum.
def sum_all(*num): # This *args parameter will accept unlimited arguments
  sum=0
  for i in num:
    sum=sum+i
  return sum
result=sum_all(1,2,3,4)
print(result)


# Write a function greet() that takes name of student and course enrolled. It has to return Hello, {name}, Welcome to {course} class. Note: If course is not passed it has to be Python in default
def greet(name, course='Python'):
  return f"Hello, {name}, Welcome to {course} class."
print(greet('Tenzin','Java'))
print(greet('Tenzin'))


"""# **Exercise 3: Function Challenge**"""
from ast import Add
# You have a numbers stored in a list as [1, -3, 0, 2, 0, 7, 10, 8, -1]. Write a function get_data(l, r, x) that find the sum of number from position l to r. If 0 lies in that given range it has to be replaced by value x.
# Example: if l = 2, r = 6 and x = 5 then sum of item from position 2 to 6 is 19. Since there are two zeros replacing it by 5 gives: 19 + 5 + 5 i.e. 29 as output.
def get_data(l,r,x):
  num_list = [1, -3, 0, 2, 0, 7, 10, 8, -1]
  selected_data=num_list[l:r+1]
  zero_count=selected_data.count(0)
  total=sum(selected_data)
  total_with_replace=total+zero_count*x
  return total_with_replace
print(get_data(2,6,5))


        # OR USING FUNCTION
num_list = [1, -3, 0, 2, 0, 7, 10, 8, -1]

def get_data(l,r,x):
  total=0
  for i in range(l,r+1):
    if num_list[i]==0:
      total+=x
    else:
      total+=num_list[i]
  return total
result=get_data(2,6,5)
print(result)