# -*- coding: utf-8 -*-
"""Functions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hbH0bJSBa16bskuYKudAT1QuA9j6lSGH

# **Function**

## **Single Argument**
"""

# -------------------------------
# 1️⃣ Simple Function Example
# -------------------------------


def greet(name):
    return f"Hello, {name}!"


message = greet("Rabi")
print(message)

message_2 = greet("Python")
print(message_2)


# -------------------------------
# 2️⃣ Function to Calculate Area
# -------------------------------


def calculate_area(radius):
    pi = 3.14
    area = pi * radius**2
    return area


area = calculate_area(5)
print(area)


# -------------------------------
# 3️⃣ Multi-Argument Function Returning Multiple Values
# -------------------------------


# Function that takes two numbers as arguments
# Returns both their product and division result
def productor(num_1, num_2):
    product = num_1 * num_2  # Multiply the two numbers
    div_n = num_1 / num_2  # Divide num_1 by num_2
    return product, div_n  # Return both results as a tuple


# -------------------------------
# Calling the function with positional arguments
# -------------------------------

a = 2
b = 3

# The function returns two values which are unpacked into prd and div
prd, div = productor(a, b)
print(prd)  # Output: 6 (2 * 3)
print(div)  # Output: 0.6666666666666666 (2 / 3)

# -------------------------------
# Calling the function with keyword arguments
# -------------------------------

# You can pass arguments in any order using parameter names
prd, div = productor(num_2=3, num_1=9)
print(prd)  # Output: 27 (9 * 3)
print(div)  # Output: 3.0 (9 / 3)


# -----------------------------------
# 🔹 1️⃣ Global Variable (Basic Access)
# -----------------------------------
num_1 = 20


def display_global():
    print(f"Access Global: {num_1}")  # OUTPUT: 20


display_global()


# -----------------------------------
# 🔹 2️⃣ Local vs Global Scope
# -----------------------------------
var_1 = 50  # Global variable


def display_local():
    var_1 = 20  # Local variable
    print(f"Inside function (Local): {var_1}")  # OUTPUT: 20


print(f"Before Invocation: {var_1}")  # OUTPUT: 50
display_local()  # OUTPUT: 20
print(f"After Invocation: {var_1}")  # OUTPUT: 50


# -----------------------------------
# 🔹 3️⃣ Local Overrides Global (Shadowing)
# -----------------------------------
num_2 = 50  # Global variable


def display_shadow():
    num_2 = 10  # Local variable (shadows global)
    print(f"Shadow Local: {num_2}")  # OUTPUT: 10


display_shadow()
print(f"Global remains: {num_2}")  # OUTPUT: 50


# -----------------------------------
# 🔹 4️⃣ Nested Function (Enclosing Scope)
# -----------------------------------
var_2 = 50  # Global variable


def display_nested():
    var_2 = 20  # Enclosing variable
    print(f"Outer function: {var_2}")  # OUTPUT: 20

    def inner_function():
        var_2 = 30  # Local to inner function
        print(f"Inner function: {var_2}")  # OUTPUT: 30

    inner_function()


print(f"Before Invocation: {var_2}")  # OUTPUT: 50
display_nested()
# OUTPUT:
# Outer function: 20
# Inner function: 30
print(f"After Invocation: {var_2}")  # OUTPUT: 50


# -----------------------------------
# 🔹 5️⃣ Modifying Global Variable using 'global'
# -----------------------------------
num_3 = 50  # Global variable


def modify_global():
    global num_3  # Refers to global variable
    num_3 = 10  # Modifies global variable
    print(f"Modified inside function: {num_3}")  # OUTPUT: 10


modify_global()
print(f"Modified globally: {num_3}")  # OUTPUT: 10
# -------------------------------
# 6️⃣ Default Arguments in Functions
# -------------------------------


def greet(name="Python"):  # assigning default value
    return f"Hello, {name}!"


default_greet = greet()
print(default_greet)  # Hello Python

engineer_greet = greet("Data Engineer")  # passing arguments while function calling
print(engineer_greet)  # Hello Data Engineer


def incrementor(var_1, increment=1):
    new_value = var_1 + increment
    return new_value


my_val = 4
incremented_value = incrementor(my_val)
print(incremented_value)  # Output: 4+1: 5

increment_non_default = incrementor(my_val, 5)
print(increment_non_default)  # Output: 4+5: 9


# -------------------------------
# 7️⃣ Args and Kwargs
# -------------------------------


# Using *args
def productor(*args):
    product = 1
    for item in args:
        product = product * item
    return product


print(productor(1))  # Output: 1
print(productor(2, 4))  # Output: 8
print(productor(3, 4, 5))  # Output: 60


# Using **kwargs
def display_info(**kwargs):
    print(kwargs)
    for key, value in kwargs.items():
        print(f"{key}: {value}")


display_info(name="John", age=25)  # output: { name: John , age:25 }

# Combining *args and operations
from functools import reduce


def perform_calculation(operation_name, *args):
    if operation_name.lower() == "sum":
        result = sum(args)
    elif operation_name.lower() == "product":
        result = reduce(lambda x, y: x * y, args)
    else:
        result = f"{operation_name} is not implemented"
    return result


sum_result = perform_calculation("sum", 1, 2, 4)
print(f"Total: {sum_result}")

product_result = perform_calculation("product", 1, 2, 4)
print(f"Product: {product_result}")

hcf_result = perform_calculation("hcf", 1, 2, 4)
print(f"HCF: {hcf_result}")


# -------------------------------
# 8️⃣ Recursive Function Example
# -------------------------------


def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n - 1)


fac_a = factorial(5)
print(fac_a)


# -------------------------------
# 9️⃣ Lambda Functions
# -------------------------------

square = lambda x: x**2
print(square(5))

sum_diff = lambda x, y: (x + y, x - y)
total, diff = sum_diff(3, 4)
print(total)
print(diff)

even_chk = lambda x: "Yes" if x % 2 == 0 else "No"
print(even_chk(4))
print(even_chk(5))


# -------------------------------
# 🔟 Filter Function Example
# -------------------------------

numbers = [1, 2, 3, 4, 5]
even_numbers = list(filter(lambda x: x % 2 == 0, numbers))
print(even_numbers)

age_list = [15, 22, 30, 17, 40]
adults = list(filter(lambda x: x >= 18, age_list))
print(adults)


# -------------------------------
# 1️⃣1️⃣ Map Function Example
# -------------------------------

numbers = [1, 2, 3, 4, 5]
squared_numbers = list(map(lambda x: x**2, numbers))
print(squared_numbers)

num_values = ["1", "2", "3"]
int_values = list(map(int, num_values))
print(num_values)
print(int_values)


# -------------------------------
# 1️⃣2️⃣ Reduce Function Example
# -------------------------------

from functools import reduce

numbers = [1, 2, 3, 4]
product = reduce(lambda x, y: x * y, numbers)
print(product)

numbers = [1, 2, 3, 4]
sum_values = reduce(lambda x, y: x + y, numbers)
print(sum_values)
