# -*- coding: utf-8 -*-
"""String Datatypes and its method.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_7P9IPPAFP8wKO65XXR0_MVclspZWD-f

**Storing String**
"""

# Storing string
sample_text1 = "Hello, World"
sample_text2 = "Hello, World"
sample_text3 = """Hello, World"""
sample_text4 = """Hello, World"""

print(sample_text1)
print(sample_text2)
print(sample_text3)
print(sample_text4)

# which quote to choose
str_1 = "Hello, I'm Learning Python"  # ' is part of data so stored inside " (you can use ''' as well)
print(str_1)

str_2 = 'Ram said, "I have a pen"'  # " is part of data so stored inside ' (you can use ''' as well)
print(str_2)

str_3 = '''Hari Said, "I've been learning Python"'''  # both ' and " is part of data so stored inside '''
print(str_3)

# Multiline string (must use tripe quote)
statement = """I have been studying since child.
  Its never ending process
We should always impose our skill
"""
print(statement)

# Escape Character
# character like \n, \t have special meaning in python.
my_str = "Hello, I am practicing string. It is said \n and \t have special meaning"
print(my_str)
print()

my_str_correct = (
    "Hello, I am practicing string. It is said \\n and \\t have special meaning"
)
print(my_str_correct)

print(
    "It's Python"
)  # When we use same quotation outside, then to print same quatation inside, USE \'
print(
    'He said "Hello"'
)  # When we use same quotation outside, then to print same quatation inside, USE \"

my_data = "I've a new laptop"
print(my_data)

"""# **String Methods**

## **Position Related**

## **Indexing**
"""

str_1 = "Python is fun"

first_character = str_1[0]  # Position Starts from zero
print(first_character)

print(str_1[3])
print(str_1[7])
print(str_1[-1])
print(str_1[-3])

"""## **Slicing**"""

s = "PYTHON"

# 1. Basic Slicing
print(s[0:4])

# 2. Without Start
print(s[:4])


# 3. Without End
print(s[2:])


# 4. Full String
print(s[:])

# 5. Using Step
print(s[0:6:2])

# 6. Reverse String
print(s[::-1])

# 7. Negative Indexing ( Always include Start and exclude end (-1)'s postion char is ignored)
print(s[-4:-1])

#  P    Y    T    H    O    N
# -6   -5   -4   -3   -2   -1
# OUTPUT: THO

"""# **Generic**

### **Concatenation**
"""

# Concatenation
hello_text = "Hello "
world_text = "world"
print(hello_text + world_text)

course = "Python"
print(course + " is fun")

"""### **Repetition**"""

# Repetition
sample_text = "hello "
repeated_text = sample_text * 3
print(repeated_text)

"""### **Length**"""

# Len
sample_string = "Python"
character_count = len(sample_string)
print(character_count)

sample_string_2 = "Data Science"
print(len(sample_string_2))

"""## **Cleanup Related**

### **Strip**
"""

# Strip
str_1 = "   Hello, World!   "
stripped_str = str_1.strip()
print(str_1)
print(stripped_str)

print("###Data # Fun###".strip("#"))  # From Both Sides
print("###Data###".lstrip("#"))  #  From left Only
print("###Data###".rstrip("#"))  # From Right Only

"""### **Split**"""

sample_text = "Learning Data Science"
splitted = sample_text.split()
print(splitted)

file_name = "2026-03-01.csv"
splitted_data = file_name.split("-")
print(splitted_data)

fruits = "apple,banana,orange"
splitted_fruits = fruits.split(",")
print(splitted_fruits)

"""### **join**"""

# Join
# split() will join all elements in the list and convert into a string
fruits = ["apple", "banana", "orange"]
joined_fruits = ", ".join(fruits)
print(joined_fruits)
print(type(joined_fruits))

date_data = ["2026", "03", "01"]
joined_date = "-".join(date_data)
print(joined_date)
print(type(joined_date))

data = "python"
joined_data = ".".join(data)
print(joined_data)
print(type(joined_data))

"""### **Find and index**"""

# Find
fruit_name = "pine apple"

e_index = fruit_name.find("e")
print(e_index)

apple_index = fruit_name.find("apple")
print(apple_index)

b_index = fruit_name.find("b")
print(b_index)

# Index
fruit_name = "pine apple"

e_index = fruit_name.index("e")
print(e_index)

apple_index = fruit_name.index("apple")
print(apple_index)

"""### **Replace**"""

text = "Hello World"
replaced_text = text.replace("World", "Python")
print(replaced_text)

date_value = "2026-03-01"
date_replaced = date_value.replace("-", "/")
print(date_replaced)

"""### **Count**"""

course = "Python"
count_str = course.count("n")
print(count_str)

# Count
python_str = "python is pretty fun. python is free"
python_count = python_str.count("python")
print(python_count)
