# -*- coding: utf-8 -*-
"""File Handling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11DyAP-Idfca7ngIkuyRdBhOvD9z5OrLm

# **Text File**

## **Read**
# Without Context Manager: A context manager is a Python feature (used with with) that automatically handles resource setup and cleanup (opening and closing)

# ### **Without Context Manager**
#"""

# # Read all data
file_obj = open(
    "/Users/urgyentsering/Desktop/Data Science/Python/File_handling/Files/file.txt", "r"
)
content = file_obj.read()
print(content)
file_obj.close()

print("-------------------------------------------------------")


"""### **With Context Manager (preferred)**"""

with open(
    "/Users/urgyentsering/Desktop/Data Science/Python/File_handling/Files/file.txt", "r"
) as file_obj:
    content = file_obj.read()
print(content)

print("-------------------------------------------------------")


# LOOP for read
with open(
    "/Users/urgyentsering/Desktop/Data Science/Python/File_handling/Files/file.txt", "r"
) as file_obj:
    for data in file_obj:
        print(data)

print("-------------------------------------------------------")


with open(
    r"/Users/urgyentsering/Desktop/Data Science/Python/File_handling/Files/nobel_prize_speech.txt",
    "r",
) as file_obj:
    file_content = file_obj.read()  # read whole file as a single string

    print(file_content)
    print(len(file_content))

print("-------------------------------------------------------")

with open(
    "/Users/urgyentsering/Desktop/Data Science/Python/File_handling/Files/nobel_prize_speech.txt",
    "r",
) as file_obj:
    content = (
        file_obj.readlines()
    )  # Reads file line by line, readlines() makes each line (sentence) an element of the list, not each word or string.

print("-------------------------------------------------------")

with open(
    "/Users/urgyentsering/Desktop/Data Science/Python/File_handling/Files/nobel_prize_speech.txt",
    "r",
) as file_obj:
    line_1 = file_obj.readline()  # read only the first line of file

print(line_1)

print("-------------------------------------------------------")


# """## **Write**"""

with open("output.txt", "w") as file_obj:
    file_obj.write("Hello, World!\n")
    file_obj.write("How are you?")

# This will overwrite the data of earlier file with same name
data_list = ["I am 'Rabindra'\n", "I am learning Python\n", "Bye\n"]
with open("output.txt", "w") as file_obj:
    file_obj.writelines(data_list)

print("-------------------------------------------------------")

data_to_write = """     Poem On Python
Python is a friendly language, fun and smart to use,
It helps us tell the computer what to do and choose.
We write simple words like print to say hello,
And watch our bright ideas start to grow and glow.
With loops and numbers, we can count and play,
Python makes coding easy every day!
"""

with open("python_poem.txt", "w") as file_obj:  # Can store to other location as well
    file_obj.write(data_to_write)

print("-------------------------------------------------------")

# APPEND: it is used to edit existence file without overwriting its data , to add additional data
# write
welcome_message = """ Hello All,
I hope you are doing well """

with open("lab.txt", "w") as file_obj:
    file_obj.write(welcome_message)

# """## **Append**"""
# # This append will add additional data in above lab.txt file
with open("lab.txt", "a") as file_obj:
    file_obj.write("\nThis has to be at end")

# """# **CSV**

# ## **Read**
# """

# # CSV as List of List
import csv

with open(
    "/Users/urgyentsering/Desktop/Data Science/Python/File_handling/Files/2022-01-02.csv",
    "r",
) as file_obj:
    reader = csv.reader(
        file_obj
    )  # It creates a CSV reader object that reads your file row by row. Each row will be returned as a list
    data = list(reader)  # It reads all rows from the CSV and converts them into a list

# print(data)

for row in data:
    print(row)

# # CSV as List of Dictionary
import csv

with open(
    "/Users/urgyentsering/Desktop/Data Science/Python/File_handling/Files/2022-01-02.csv",
    "r",
) as file_obj:
    reader = csv.DictReader(file_obj)
    data = list(reader)

# print(data)
for row in data:
    print(row)

# """## **Write**"""

# # From List of List: converting list into CSV file
import csv

student_info = [["Rabindra", 30], ["Hari", 25]]  # this is a list
header_name = ["Name", " Age"]
with open("output.csv", "w", newline="") as file_obj:
    csv_writer = csv.writer(file_obj)
    csv_writer.writerow(header_name)  #  for header a single row
    csv_writer.writerows(student_info)  # for multiple data

# # From List of dictionary
import csv


student_info = [
    {"Name": "Rabindra", "Age": 30},
    {"Name": "Hari", "Age": 25},
]  # this is list of dictionary

with open("output2.csv", "w", newline="") as file_obj:
    headers = ["Name", "Age"]
    csv_writer = csv.DictWriter(file_obj, fieldnames=headers)
    csv_writer.writeheader()
    csv_writer.writerows(student_info)

# """# **JSON**


# """## **Read**"""

# # Reading Election Json file
import json

with open(
    "/Users/urgyentsering/Desktop/Data Science/Python/File_handling/Files/election_result.json",
    "r",
) as file_obj:
    data = json.load(file_obj)
print(data)


# """## **Write**"""

# Converting List of dictionaries into json file

import json

# This is a list of dictionaries
data = [
    {"name": "Ram", "course": "Python", "age": 25},
    {"name": "Shyam", "course": "Javascript", "age": 30},
    {"name": "Hari", "course": "Data Science", "age": 22},
]

with open("output.json", "w") as file_obj:
    json.dump(data, file_obj, indent=4)  # indent=4 will show data in different rows


# ## **Serialization**
# """

# import json

# data = {"name": "Rabindra", "age": 30}
# json_string = json.dumps(data)
# print(json_string)

# print(type(data))
# print(type(json_string))

# """## **Deserialization**"""

# import json

# json_string = '{"name": "Rabindra", "age": 30}'
# data = json.loads(json_string)
# print(data["name"])

# print(type(json_string))
# print(type(data))
