# -*- coding: utf-8 -*-
"""Loops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YVwvrAl6M_QatdspzUwokUX9zwluZg0m

# **For Loop**
"""
# for loop in tuple
countries = ("us", "china", "nepal")
for country in countries:
    if country == "nepal":
        print("Nepal is found")
print(countries)

# for loop using range
for iterator in range(1, 11):
    print(
        f"{iterator:2} ^ 2 = {iterator**2:3}"
    )  # :2 → minimum width = 2 spaces. ,  :3 → minimum width = 3 spaces

"""
      OUTPUT: 
    1 ^ 2 =   1
    2 ^ 2 =   4
    3 ^ 2 =   9
    4 ^ 2 =  16
    5 ^ 2 =  25
    6 ^ 2 =  36
    7 ^ 2 =  49
    8 ^ 2 =  64
    9 ^ 2 =  81
    10 ^ 2 = 100 

"""

# for loop in dictionary
dict_items = {
    "python": ["data science", "web-development", "automation"],
    "java": ["web-development", "desktop app"],
}
for key, value in dict_items.items():
    print(f"{key} = {value}")
    print(f"{key} is used for {', '.join(value)}")


"""
OUTPUT: 
    python = ['data science', 'web-development', 'automation']
    python is used for data science, web-development, automation
    java = ['web-development', 'desktop app']
    java is used for web-development, desktop app
"""

# 🔥 Key Concept:
# .items() → gives key + value
# join() → converts list → string
# ', '.join(value) → adds comma + space between items

"""# **While Loop**"""

# Print numbers from 1 to 10.
num = 1
while num <= 10:
    print(num)
    num = num + 1

# Print even numbers less 10
i = 0
while i < 10:
    if i % 2 == 0:
        print(i)
    i += 1

fruits = ["apple", "banana", "papaya"]
i = 0
while i < len(fruits):
    print(fruits[i])
    i += 1


"""# **Transfer**"""

# Break
user_list = ["Ram", "Shyam", "Hari", "Rabi", "Krishna"]
for user in user_list:
    print(user)
    if user == "Shyam":
        print("No need to iterate after Shyam")
        break

# Continue
user_list = ["Ram", "Shyam", "Hari", "Rabi", "Krishna"]
for user in user_list:
    if user == "Shyam":
        print("Shyam doesn't need evaluation.")
        continue
    print(user.upper())


# Using break and continue with numbers
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print("\nUsing break to stop at 5:")  # Prints header for break demo
for num in numbers:
    if num == 5:
        break
    print(num)
""" 
OUTPUT:
    Using break to stop at 5:
    1
    2
    3
    4 
"""
print("\nUsing continue to skip 5 number:")  # Prints header for continue demo
for num in numbers:
    if num == 5:
        continue
    print(num)

"""
    OUTPUT: 
    Using continue to skip 5 number:
    1
    2
    3
    4
    6
    7
    8
    9
    10
"""


"""# **For - Else**"""

user_list = ["Ram", "Hari", "Rabi", "Krishna"]
for user in user_list:
    print(user)
    if user == "Shyam":
        print("User Found")
        break
else:
    print("User not found")

"""# **Nested Loop**"""

# Try visualizing with https://pythontutor.com/
# Printing multiplication tables using nested loop
for num in range(1, 4):
    print()
    print(f"Table of {num}")
    for iterator in range(1, 6):
        print(f"{num} * {iterator} = {num*iterator}")

"""# **List Comprehension**"""

# generating list without comprehension
list_a = [1, 4, 7]
new_list_a = list()
for item in list_a:
    new_salary = item * 2
    new_list_a.append(new_salary)
print(list_a)
print(new_list_a)

# generating  list with Comprehension
new_list_with_com = [item * 2 for item in list_a]
print(new_list_with_com)

# generating  list with Comprehension with if condition
list_with_if = [item * 2 for item in list_a if item % 2 == 0]
print(list_with_if)

# generating  list with Comprehension with if  and else condition
new_list_a = [item * 2 if item % 2 == 0 else item + 10 for item in list_a]
print(new_list_a)


# Convert country names to uppercase using set comprehension
country_names = ["Nepal", "usa", "UK"]
country_upper = {country.upper() for country in country_names}
print(country_upper)
# {'NEPAL', 'UK', 'USA'}


"""# **Dictionary Comprehension**"""

# Create a dictionary with country names as keys and their lengths as values using dictionary comprehension
countries = ["Nepal", "usa", "UK"]
country_dict = {country: len(country) for country in countries}
print(country_dict)
# {'Nepal': 5, 'usa': 3, 'UK': 2}

# Increase employee salaries by 10% and uppercase employee IDs using dictionary comprehension
sample_dict = {"e1": 100, "e2": 200}
new_dict = {
    emp.upper(): round(1.1 * sal, 2) for emp, sal in sample_dict.items()
}  # increases a salary value (sal) by 10% and rounds the result to 2 decimal places
print(new_dict)

# Output: {'E1': 110.0, 'E2': 220.0}
